### PR TITLE
optimized the german translation in Arduino_de.js and Blockly_de.js

### PR DESCRIPTION
**Pull request by Kimosaj**
Hello I'm very interested in this project and wanted to help translating this in to my native language German. So here is my first commit, but it is not finished yet. I will commit more changes in the next weeks.

These are the changes I made for now:
- changed some words
- changed some symbols to more child friendly ones
- added Blockly.Msg.CAT_BUZZER

P.S.: My Prettier addon in VS Code made some changes to the layout of the code. I hope these changes are ok. :smile:

### CODE REVIEW

**Comment by Kimosaj** [comment]
Status of my work:
-------------------------------------------------------------------------------------------------------

**Arduino_de.js sections:**
- [x] Electron window
- [x] common to all blocks
- [x] categories (menu)
- [ ] DISPLAY 7 SEGMENT TM1637
- [ ] RTC DS3231
- [ ] Wireless
- [ ] INTERRUPTION
- [ ] FIELDDROPDOWN
- [ ] sensor
- [ ] bluetooth
- [ ] LCD screen
- [ ] structure
- [ ] matrix
- [ ] time
- [ ] OLED
- [ ] LED
- [ ] output
- [ ] input
- [ ] audio
- [ ] servomotor
- [ ] engine
- [ ] serial
- [ ] software serial
- [ ] ESP8266
- [ ] SIMPLE SENSORS
- [ ] CCS811
- [ ] LCD I2C
- [ ] GESTURE SENSOR APDS9960
- [ ] REMOTE CONTROL IR
- [ ] REMOTE CONTROL MRT
- [ ] OPEN SMART MP3
- [ ] Mu Vision
- [ ] LED color type
- [ ] Vision Zoom
- [ ] Vision Level
- [ ] UART status
- [ ] Vision type
- [ ] Card type
- [ ] Vision state
- [ ] True False
- [ ] Enable Disable
- [ ] Camera AWB
- [ ] Other
- [ ] Light sensor
- [ ] AT WiFi
- [ ] SOFTWARE SERIAL FOR BT
- [ ] SOFTWARE SERIAL
- [ ] SERIAL
- [ ] DISPLAY TFT ST7735
- [ ] TCS34725 color sensor
- [ ] HMC5883 compass sensor
- [ ] RADIO TEA5767
- [ ] RFID MFRC522
- [ ] NFC PN532
- [ ] KEYBOARD AND MOUSE
- [ ] GPS
- [ ] TM1640
- [ ] MOTOR MRT
- [ ] STEPPERS
- [ ] WiFi basic functions
- [ ] IFTTT
- [ ] MQTT
- [ ] RTC DS3231
- [ ] MAX7219-Led Matrix panel
- [ ] Thingspeak
- [ ] Firebase
- [ ] Telegram
- [ ] OpenWeather
- [ ] ESP8266
- [ ] Wifi Server
- [ ] Text with more functions
- [ ] Conversions
- [ ] Encoder
- [ ] ESP-NOW
- [ ] ALEXA
-------------------------------------------------------------------------------------------------------

- [ ] Blockly_de.js

**Comment by cparrapa** [comment]
@Kimosaj great initiative you might want to look at this other PR https://github.com/OttoDIY/blockly/pull/163 maybe we can combine it with yours so that we can merge all?

Thanks

**Comment by Kimosaj** [comment]
> @Kimosaj great initiative you might want to look at this other PR #163 maybe we can combine it with yours so that we can merge all?
> 
> Thanks

I saw this Request but because there wasn´t anything done since April I thought this request is outdated.

**Comment by cparrapa** [comment]
you are right @Kimosaj  might have been abandoned by @DiWoWet

**Comment by Kimosaj** [comment]
> you are right @Kimosaj might have been abandoned by @DiWoWet

@cparrapa so what to do know? I mean would be a pity if the stuff whats was finished by @DiWoWet would´nt be implemented. But I dont know how to merge this into my work.

**Comment by DiWoWet** [comment]
Hey guys,
I'm sorry to tell you that I simply forgot working on the translation and finishing it. There were only minor issues and I think that I am going to have another look at it until new years eve. 

Richtig dumm gelaufen und richtig unangenehm. :D :D :D

**Comment by Kimosaj** [comment]
@cparrapa I finally found the time again to keep working on the translation. Today I tried to build the app with the translation I made so far to look if everything is how I expected. But because I have no experience with building apps from source code I ran into some trouble with errors. I f I want to execute npm install there is this error: 
`npm ERR! code EJSONPARSE
npm ERR! JSON.parse Failed to parse json
npm ERR! JSON.parse Unexpected token / in JSON at position 751 while parsing near '...--win --ia32",
npm ERR! JSON.parse     //"compiler": "build...'
npm ERR! JSON.parse Failed to parse package.json data.
npm ERR! JSON.parse package.json must be actual JSON, not just JavaScript.`

**Comment by cparrapa** [comment]
not sure what that error means @Kimosaj  but what you can do is just attach the _de.js and i can add those changes for next release that we plan to make this month, otherwise you will have to wait for next release for the changes to be added

**Comment by Kimosaj** [comment]
@cparrapa I can't attach the single file to a comment. Is it possible to merge this pull request even it is in draft? If yes I have to merge my branch where I'm working on to my linked master-branch.

**Comment by cparrapa** [comment]
Hi @Kimosaj  
Github says "This pull request is still a work in progress. Draft pull requests cannot be merged."

So you have to update your main branch and I will wait for your PR and we can merge even if is not completely ready

**Comment by Kimosaj** [comment]
don't know why this happened 😅

**Comment by cparrapa** [comment]
Thanks good job! @Kimosaj  merging now

**Pull request merged**
