### PR TITLE
Add support for selecting old/new Arduino Nano

### PR DESCRIPTION
**Pull request by BodoMinea**
Updated bootloader requires higher (double) upload speed

### CODE REVIEW

**Comment by cparrapa** [comment]
Hi @BodoMinea thanks for the contribution, just to double confirm before merge, you are using the new Arduino Nano every? was this issue not letting you upload to old genuino nano? because with "old" nano clones we were to use without any problem by installing the CH340 driver.

**Comment by BodoMinea** [comment]
Hi, no, this is not about the Arduino every or BLE. Not an old clone either (those are working, and I do have the CH340 installed because I sometimes program NodeMCU boards). It is a newly built, regular Arduino Nano acquired from a local supplier. The only difference is the bootloader. This one has an upgraded bootloader which requires a higher upload speed.

You can see this issue discussed on another project which requires uploading to Arduino boards back in 2018:
https://github.com/twinearthsoftware/ArduinoSketchUploader/issues/32

**Comment by cparrapa** [comment]
Hi @BodoMinea 
Do you also experience the glitch with the servo blocks in this online version?, do you know how to fix this is very strange.

Thanks

**Comment by BodoMinea** [comment]
Hi.
I do not know what servo glitch you are talking about. This PR is only about the different nano revisions. I used both Otto Blockly and Arduino IDE to program the robots and had no trouble with the servos.
Do you have a link to show me what´s wrong? Maybe I can come up with something.

**Comment by cparrapa** [comment]
Hi
I will merge this now even do i have no way to test, (all my nanos work so far) but as you said maybe some people have new nanos. In any case i am working on a major update of this repo and does not interfere with this.

The servos and other blocks have this issue https://wikifactory.com/+OttoDIY/forum/category/NzI?thread=Mjk5OTAz

Thanks

**Comment by BodoMinea** [comment]
I checked and it is happening on the online demo that is linked here on GH, but it is working fine in the installed version.

**Comment by cparrapa** [comment]
Yes is just weird that in the online it disappear i was thinking that was probably related to the naming of the  .js files because the have underscore at the beginning like _actionneur.js and those are the ones that particularly do not load

**Comment by BodoMinea** [comment]
Hmm, this seems to be a weird quirk of the Jekyll webserver that Github uses for the Pages thing.

So you have files that start with underscores and files that do not in the blocs&generateurs folder, and the underscore ones are not served. 

After some googling around I found that this apparently is a feature on Jekyll. Those are treated as special files or something.
See the issues: https://github.com/jekyll/jekyll/issues/55, https://github.com/jekyll/jekyll/issues/324, https://github.community/t5/GitHub-Pages/Cannot-access-underscore-folder-file-with-nojekyll/m-p/36088#M2287

Apparently the solutions could be:
- commit a „..nojekyll” file to the root of the repo if you do not need Jekyll preprocessing tags/rules at all
- just rename the files to not use underscores and update the includes accordingly

This would solve the 404 errors and probably the missing blocks.

**Comment by cparrapa** [comment]
Good find!
I am ok with renaming them, we just need to make sure it is also renamed in the files that use them and doesn't create some errors reaction.

**Pull request merged**
