### PR TITLE
extended German translation /w added escornabot reference

### PR DESCRIPTION
**Pull request by DiWoWet**
This is an extended German translation for OttoBlockly. I already used and thus tested it as a means to convey basic programming skills in grade 7. As my course and I started working on the OttoDIY build last October (ver 1.4.3), I noticed a vast amount of problems with the German translation as it was still coined with many English terms which were hard to grasp for my students. As a consequence I edited the language files in order to improve the use of OttoBlockly for German students.  

Looking forward to edits, commits and comments.

### CODE REVIEW

**Comment by cparrapa** [comment]
Looking good @DiWoWet 
I see also the otto.js did you make a considerable change?

**Comment by DiWoWet** [comment]
Actually I did three changes in line 268, 282 and 296 (added three references [Blockly.Msg.OTTO9_QUAD_HELLO, Blockly.Msg.OTTO9_QUAD_JUMP,  Blockly.Msg.OTTO9_QUAD_SCARED]) to make future translations more accessible. However, I haven't added the references to the other language files yet... now, that you mentioned it this may be problematic as it would lead to a missing translation and therefore some random text in blockly... two possible solutions: 1. every language file would have to be "modified" with the new reference or 2. let's keep the original otto.js and German students just have to cope with three English blocks for OTTO_Quad. What do you think? I could do the modification for the other language files within the next three days and set up another pull request (?).

**Comment by DiWoWet** [comment]
@cparrapa committed another change for similar reasons in escornabot.js (l. Blockly.Msg.ESCORNABOT_AUTONOM).

**Comment by cparrapa** [comment]
Great, thanks I am checking then so that other languages are not affected by this change

**Comment by cparrapa** [comment]
Hi @DiWoWet 
It seems there are some conflicts that must be resolved but I can't see exactly where

**Comment by cparrapa** [comment]
@DiWoWet  there has been another PR with same objective https://github.com/OttoDIY/blockly/pull/187 you can also help us check if something is missing for now I will close this PR

**Pull request closed without merging**
